### ISSUE TITLE
Optional constraints 

### ISSUE THREAD

**Issue by RajaReddyiOS** [bhlvoong/LBTAComponents#18] opened 2017-08-29 13:43 UTC
how to assign optional constraints like height as greaterthan or equal some constant
height anchor >= 40 like this

**Comment by ZacharyKhan** [comment] 2017-12-06 01:07
@bhlvoong Please close as a duplicate of #17, I have submitted my answer there.

**Closed as completed** 2017-12-07 06:21 UTC
